name: Yongold
title: Yongold | A blog  for old people
description: "Yongold is a blog care about old people "
tags:
  - blog
  - old
  - Young
show_hero: true
paginate: 10
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: youremail@xyz.com
disqus_username: disqus_username
